[package]
name = "aoc22"
# year.month.day
version = "2022.12.16"

[addresses]
std =  "0x1"
aoc22 = "0xc0de"
extralib = "0x72a"

[dependencies]
MoveStdlib = { git = "https://github.com/move-language/move.git", subdir = "language/move-stdlib", rev = "4901410d1f510601ca7fb982989e02c00756cac6" }
MoveNursery = { git = "https://github.com/move-language/move.git", subdir = "language/move-stdlib/nursery", rev = "4901410d1f510601ca7fb982989e02c00756cac6" }
ExtraLib = { local = "../extralib" }
